---
# The order here matters
- name: restart telegraf
  service:
    name: telegraf
    state: restarted

- name: pause
  pause:
    seconds: "{{telegraf_start_delay}}"

## After version 2.2 of ansible 'listen' could be used to
## group 'check status' and 'assert running' into a single listener
- name: check status
  command: service telegraf status
  ignore_errors: yes
  register: telegraf_service_status
- name: assert running
  assert:
    that:
      - "telegraf_service_status.rc == 0"
